version: "3.1"
services:
  saasform-db:
    image: postgres
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./data/db:/var/lib/postgres:cached

  saasform:
    image: saasform/saasform:latest
    build: ./src/webapp
    restart: always
    depends_on:
      - saasform-db
    environment:
      - NODE_ENV=development
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=localhost
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres
      - TYPEORM_DATABASE=postgres
      - TYPEORM_PORT=5432
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=true
      - TYPEORM_MIGRATIONS=/app/dist/migration/**/*.js
      - HUMBUG_TOKEN=3bafba59-f078-4004-ab12-fa27cf4885f1
    ports:
      - "7000:7000"
    volumes:
      - ./data/config:/app/config
      - ./data/emails:/app/emails
      - ./data/pages:/app/pages
      - ./data/themes:/app/themes
    command: ["bash", "/app/bin/startup.sh"]

  demo-express:
    image: saasform/demo-express:latest
    restart: always
    depends_on:
      - saasform
    environment:
      SAASFORM_SERVER: http://172.31.35.177:7000
      SAASFORM_USER_LOGIN: http://172.31.35.177:7000/login
    ports:
      - "3000:3000"
    command: ["wait-for-it",  "saasform:7000", "--", "npm", "start"]
